packages:
  - 'apps/*'
  - 'packages/*'

verifyDepsBeforeRun: false
autoInstallPeers: true
strictPeerDependencies: false

allowBuilds:
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true
