<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Binexus.Modules.Inventory</RootNamespace>
    <AssemblyName>Binexus.Modules.Inventory</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Binexus.Modules.Inventory.Contracts\Binexus.Modules.Inventory.Contracts.csproj" />
    <ProjectReference Include="..\..\Binexus.SharedKernel\Binexus.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Binexus.Platform\Binexus.Platform.csproj" />
  </ItemGroup>
</Project>
