<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Binexus.Platform\Binexus.Platform.csproj" />
    <ProjectReference Include="..\..\src\Modules\Binexus.Modules.Identity\Binexus.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Binexus.Modules.Inventory\Binexus.Modules.Inventory.csproj" />
    <ProjectReference Include="..\..\src\Modules\Binexus.Modules.Logistics\Binexus.Modules.Logistics.csproj" />
    <ProjectReference Include="..\..\src\Modules\Binexus.Modules.Orders\Binexus.Modules.Orders.csproj" />
    <ProjectReference Include="..\..\src\Modules\Binexus.Modules.Sales\Binexus.Modules.Sales.csproj" />
    <ProjectReference Include="..\..\src\Modules\Binexus.Modules.Warehouse\Binexus.Modules.Warehouse.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
